routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

    return view('welcome');
});

Route::group(['middleware' => 'auth'], function () {

    Route::resource('photos', 'PhotoController');

});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('schools', 'SchoolController');

Route::get('schools/{school}/students/photo-entry-forms/preview', 'StudentController@previewPhotoEntryForms')->name('schools.students.photo-entry-forms.preview');

Route::post('schools/{school}/students/photo-entry-forms/download', 'StudentController@downloadPhotoEntryForms')->name('schools.students.photo-entry-forms.download');


Route::resource('schools.students', 'StudentController');

Route::post('schools/{school}/students', 'StudentController@upload')->name('schools.students.upload');

Route::post('schools/{school}/students/photos', 'PhotoController@upload')->name('schools.students.photos.upload');

app/Models/Photo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Photo extends Model
{
    protected $fillable = ['user_id', 'path'];
}

app/Http/Controllers/PhotoController.php
<?php

namespace App\Http\Controllers;

class PhotoController extends Controller
{
    public function index()
    {
        $photos = auth()->user()->photos;
        return view('photos.index', compact('photos'));
    }

    public function create()
    {
        return view('photos.create');
    }

    public function upload($id)
    {
        $school = auth()->user()->schools()->findOrFail($id);

        request()->validate([
            'file_id' => 'string|required|url',
        ]);

        $file_id = request()->file_id;

        $photos = [];

        for ($i = 0; $i < $this->getNumberOfFiles($file_id); $i++) {
            $photos[] = $file_id . 'nth/' . $i . '/';
        }

        if ($school->studentsCount() !== $this->getNumberOfFiles($file_id)) {
            return back();
        }

        foreach ($school->students as $index => $student) {
            $student->photo_hash = bin2hex(random_bytes(20));
            $student->photo_url = $photos[$index];
            $student->save();
        }

        return back();
    }

    public function getNumberOfFiles($file_id)
    {
        return (int)substr($file_id, -2, 1);
    }
}

resources/views/photos/create.blade.php
@extends('layouts.app')

@section('content')   
    
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Upload Photos</h3>
                    </div>
                    <div class="panel-body">
                        <form action="{{ route('photos.store') }}" method="POST" enctype="multipart/form-data">
                            {{ csrf_field() }}

                            <div class="form-group">
                                <input type="file" name="photos[]" multiple>
                            </div>

                            <button type="submit" class="btn btn-primary">Upload</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>     
@endsection

resources/views/photos/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-heading">Photos</div>

                <div class="panel-body">
                   @foreach($photos->chunk(6) as $photoSet)
                        <div class="row">
                            @foreach($photoSet as $photo)
                                <div class="col-sm-2 col-xs-2">
                                    <img src="{{ asset('storage/' . $photo->path) }}" class="img-responsive thumbnail" alt="Image">
                                </div>
                            @endforeach
                        </div>
                   @endforeach
                </div>
            </div>
        </div>
    </div>
</div>
@endsection