routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

    return view('welcome');
});

Route::group(['middleware' => 'auth'], function () {

    Route::resource('photos', 'PhotoController');

});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('schools', 'SchoolController');

Route::get('schools/{school}/students/photo-entry-forms/preview', 'StudentController@previewPhotoEntryForms')->name('schools.students.photo-entry-forms.preview');

Route::post('schools/{school}/students/photo-entry-forms/download', 'StudentController@downloadPhotoEntryForms')->name('schools.students.photo-entry-forms.download');


Route::resource('schools.students', 'StudentController');

Route::post('schools/{school}/students', 'StudentController@upload')->name('schools.students.upload');

Route::post('schools/{school}/students/photos', 'PhotoController@upload')->name('schools.students.photos.upload');

app/Models/School.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class School extends Model
{
    public function region()
    {
        return $this->belongsTo(Region::class);
    }

    public function district()
    {
        return $this->belongsTo(District::class);
    }

    public function schoolLevel()
    {
        return $this->belongsTo(SchoolLevel::class);
    }

    public function students()
    {
        return $this->hasMany(Student::class);
    }

    public function studentsCount()
    {
        return $this->students()->count();
    }
}

app/Http/Controllers/SchoolController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class SchoolController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $schools = auth()->user()->schools;
        return view('schools.index', compact('schools'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $school = auth()->user()->schools()->findOrFail($id);
        return view('schools.show', compact('school'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/schools/index.blade.php
@extends('layouts.dashboard')

@section('title', 'Schools')

@section('content')

    <div class="row">
        <div class="col-md-4">
            <div class="card">
                <div class="content">
                    <a href="{{ route('schools.create') }}" class="btn btn-primary">New School</a>
                </div>
            </div>
        </div>        
    </div>

    <div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="header">
                <h4 class="title">Schools</h4>
            </div>
            <div class="content table-responsive table-full-width">
                <table class="table table-hover table-striped">
                    <thead>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Index</th>
                    <th>Region</th>
                    <th>District</th>
                    <th>Level</th>
                    <th>Date</th>
                    </thead>
                    <tbody>
                    @php $i = 1 @endphp
                    @foreach($schools as $school)
                        <tr>
                            <td>{{ $i++ }}.</td>
                            <td>
                                <a href="{{ route('schools.show', $school) }}">
                                    {{ $school->name }}
                                </a>
                            </td>
                            <td>{{ $school->index_number }}</td>
                            <td>{{ $school->region->name }}</td>
                            <td>{{ $school->district->name }}</td>
                            <td>{{ $school->schoolLevel->name }}</td>
                            <td>{{ $school->created_at }}</td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>

            </div>
        </div>
    </div>        
    </div>

@endsection

resources/views/schools/show.blade.php
@extends('layouts.dashboard')

@section('title', $school->name)

@section('content')

    <div class="col-md-12">
        <div class="card">
            <div class="header">
                <h4 class="title">{{ $school->name }}</h4>
            </div>
            <div class="content">
               
               <div class="row">
                   <div class="col-md-6">
                       <div class="table table-responsive">
                           <table class="table table-bordered">
                               <tbody>
                                   <tr>
                                       <th>Name</th>
                                       <td>{{ $school->name }}</td>
                                   </tr>
                                   <tr>
                                       <th>Index</th>
                                       <td>{{ $school->index_number }}</td>
                                   </tr>
                                   <tr>
                                       <th>Region</th>
                                       <td>{{ $school->region->name }}</td>
                                   </tr>
                                   <tr>
                                       <th>District</th>
                                       <td>{{ $school->district->name }}</td>
                                   </tr>
                                   <tr>
                                       <th>Students</th>
                                       <td>{{ $school->studentsCount() }}</td>
                                   </tr>
                                   <tr>
                                       <td>&nbsp;</td>
                                       <td>
                                           <a href="{{ route('schools.students.index', $school->id) }}" class="btn btn-primary">Students</a>
                                       </td>
                                   </tr>
                               </tbody>
                           </table>
                       </div>                       
                   </div>
               </div>

            </div>
        </div>
    </div>

@endsection