routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {

    return view('welcome');
});

Route::group(['middleware' => 'auth'], function () {

    Route::resource('photos', 'PhotoController');

});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('schools', 'SchoolController');

Route::get('schools/{school}/students/photo-entry-forms/preview', 'StudentController@previewPhotoEntryForms')->name('schools.students.photo-entry-forms.preview');

Route::post('schools/{school}/students/photo-entry-forms/download', 'StudentController@downloadPhotoEntryForms')->name('schools.students.photo-entry-forms.download');


Route::resource('schools.students', 'StudentController');

Route::post('schools/{school}/students', 'StudentController@upload')->name('schools.students.upload');

Route::post('schools/{school}/students/photos', 'PhotoController@upload')->name('schools.students.photos.upload');

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    protected $fillable = [
        'first_name',
        'middle_name',
        'last_name',
        'gender',
        'index_number',
        'school_id',
    ];

    public function photo($width = 132, $height = 185)
    {
        return $this->photo_url . '-/resize/' . $width . 'x' . $height . '/';
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Student;
use Barryvdh\DomPDF\Facade as PDF;
use Maatwebsite\Excel\Facades\Excel;

class StudentController extends Controller
{
    public function index($id)
    {
        $school = auth()->user()->schools()->findOrFail($id);

        $students = $school->students;

        return view('students.index', compact('school', 'students'));
    }

    public function create($id)
    {
        $school = auth()->user()->schools()->findOrFail($id);
        return view('students.create', compact('school'));
    }

    public function upload($id)
    {
        $school = auth()->user()->schools()->findOrFail($id);

        // validation

        $rows = Excel::load(request()->file('file'), function ($reader) {

        })->get();

        foreach ($rows as $row) {
            $student = new Student;
            $student->first_name = $row->first_name;
            $student->middle_name = $row->middle_name;
            $student->last_name = $row->last_name;
            $student->gender = $row->gender;
            $student->index_number = $row->index_number;

            $school->students()->save($student);
        }

        return redirect()->route('schools.students.index', $school->id);
    }

    public function previewPhotoEntryForms($id)
    {
        $school = auth()->user()->schools()->findOrFail($id);
        return view('pdf.forms.photo-entry', compact('school'));
    }

    public function downloadPhotoEntryForms($id)
    {
        $school = auth()->user()->schools()->findOrFail($id);

        $view = view('pdf.forms.photo-entry', compact('school'))->render();

        $pdf = PDF::loadHtml($view);

        return $pdf->stream($school->name . '.pdf');
    }
}

resources/views/students/create.blade.php
@extends('layouts.dashboard')

@section('title', $school->name)

@section('content')

    <div class="col-md-12">
        <div class="card">
            <div class="header">
                <h4 class="title">Upload Students</h4>
            </div>
            <div class="content">
                
                <form action="{{ route('schools.students.upload', $school->id) }}" method="POST" enctype="multipart/form-data">
                    {{ csrf_field() }}

                    <div class="form-group">
                        <input type="file" name="file" required>
                    </div>

                    <button type="submit" class="btn btn-primary">Upload</button>
                </form>

            </div>
        </div>
    </div>

@endsection

resources/views/students/index.blade.php
@extends('layouts.dashboard')

@section('title', $school->name . ' Students')

@section('content')

    @if($school->students->count())

        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <div class="header">
                        <h4 class="title">Upload Photos</h4>
                    </div>
                    <div class="content">

                        <form action="{{ route('schools.students.photos.upload', $school->id) }}" method="POST" role="">
                            {{ csrf_field() }}

                            <input type="hidden" role="uploadcare-uploader" name="file_id" data-upload-url-base=""
                                   data-tabs="file" data-multiple=""/>

                            <button type="submit" class="btn btn-primary">Upload</button>
                        </form>

                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <div class="header">
                        <h4 class="title">Photo Entry Forms</h4>
                    </div>
                    <div class="content">

                        <div class="row">
                            <div class="col-sm-6">
                                <a href="{{ route('schools.students.photo-entry-forms.preview', $school->id) }}" class="btn btn-primary">Preview</a>
                            </div>
                            <div class="col-sm-6">
                               <form action="{{ route('schools.students.photo-entry-forms.download', $school->id) }}" method="POST">
                                   {{ csrf_field() }}

                                   <button type="submit" class="btn btn-default">Download</button>
                               </form>                                
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>

    @endif

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="header">
                    <h4 class="title">{{ $school->name }} Students</h4>
                </div>
                <div class="content {{ $school->students->count() ? 'table-responsive table-full-width' : '' }}">
                    @if($school->students->count())
                        <table class="table table-hover table-bordered">
                            <thead>
                            <th>ID</th>
                            <th>Index</th>
                            <th>First name</th>
                            <th>Middle name</th>
                            <th>Last name</th>
                            <th>Gender</th>
                            <th>Photo</th>
                            </thead>
                            <tbody>
                            @php $i = 1 @endphp
                            @foreach($students as $student)
                                <tr>
                                    <td>{{ $i++ }}.</td>
                                    <td>{{ $student->index_number }}</td>
                                    <td>{{ $student->first_name }}</td>
                                    <td>{{ $student->middle_name }}</td>
                                    <td>{{ $student->last_name }}</td>
                                    <td>{{ $student->gender }}</td>
                                    <td>
                                        @isset($student->photo_url)
                                        <img src="{{ $student->photo() }}" alt="">
                                        @endisset
                                        @empty($student->photo_url)
                                            <i class="pe-7s-user icon-user"></i>
                                        @endempty
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    @else

                        <div class="description text-center">
                            <p>
                                No Students
                            </p>
                            <a href="{{ route('schools.students.create', $school->id) }}"
                               class="btn btn-primary">Upload</a>
                        </div>

                    @endif

                </div>

            </div>
        </div>
    </div>

@endsection

@push('scripts')

    <script>
        UPLOADCARE_LIVE = false;
        UPLOADCARE_IMAGES_ONLY = true;
    </script>

    {!! Uploadcare::scriptTag() !!}
    
@endpush